server:
  port: 4040
  name: github.com/SliverFlow/ksmall/HttpServer/search
log:
  level: info
  prefix: 'github.com/SliverFlow/ksmall/HttpServer/search'
  format: console
  director: 'log/http/search'
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  max-age: 0
  show-line: true
  log-in-console: true