server:
  port: 6060
  name: 'github.com/SliverFlow/ksmall/HttpServer/user'
  timeout: 5

log:
  level: info
  prefix: 'github.com/SliverFlow/ksmall/HttpServer/user'
  format: console
  director: 'log/http/user'
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  max-age: 0
  show-line: true
  log-in-console: true

userRpc:
  type: 'direct' # direct 直联 ，etcd 为使用 etcd 注册中心
  ip: '127.0.0.1:6061'
