server:
  port: 5050
  name: github.com/SliverFlow/ksmall/httpserver/shopcart
log:
  level: info
  prefix: 'github.com/SliverFlow/ksmall/httpserver/shopcart'
  format: console
  director: 'log/shopcart'
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  max-age: 0
  show-line: true
  log-in-console: true