server:
  port: 3030
  name: github.com/SliverFlow/ksmall/httpserver/order
log:
  level: info
  prefix: 'github.com/SliverFlow/ksmall/httpserver/order'
  format: console
  director: 'log/order'
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  max-age: 0
  show-line: true
  log-in-console: true