server:
  port: 2020
  name: "github.com/SliverFlow/ksmall/HttpServer/goods"
log:
  level: info
  prefix: 'github.com/SliverFlow/ksmall/HttpServer/goods'
  format: console
  director: 'log/http/goods'
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  max-age: 0
  show-line: true
  log-in-console: true