server:
  port: 1010
  name: 'github.com/SliverFlow/ksmall/HttpServer/category'
log:
  level: info
  prefix: 'github.com/SliverFlow/ksmall/HttpServer/category'
  format: console
  director: 'log/http/category'
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  max-age: 0
  show-line: true
  log-in-console: true